Update main.yml
Update dev-drprasad to v0.2.1 because :
Error: Unable to resolve action `dev-drprasad/delete-tag-and-release@v0.2.0`, unable to find version `v0.2.0`